    DROP TABLE IF EXISTS LOESUNGEN;
    DROP TABLE IF EXISTS AUFGABEN;
    DROP TABLE IF EXISTS ERKLAERUNGEN;
    DROP TABLE IF EXISTS KAPITEL;
    DROP TABLE IF EXISTS KURSE;
    DROP TABLE IF EXISTS THEMA;
    DROP TABLE IF EXISTS FAECHER;


    CREATE TABLE FAECHER
    (
        ID   INT AUTO_INCREMENT PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL
    );

    CREATE TABLE THEMA
    (
        ID         INT AUTO_INCREMENT PRIMARY KEY,
        NAME       VARCHAR(255) NOT NULL,
        FAECHER_ID INT,
        FOREIGN KEY (FAECHER_ID) REFERENCES FAECHER (ID) ON DELETE CASCADE
    );

    CREATE TABLE KURSE
    (
        ID      INT PRIMARY KEY AUTO_INCREMENT,
        KURS_NR      INT          ,
        TITEL        VARCHAR(255) ,
        AUTHOR       VARCHAR(255) ,
        IMG          VARCHAR(255),
        BESCHREIBUNG VARCHAR(255),
        THEMA_ID     INT,
        FOREIGN KEY (THEMA_ID) REFERENCES THEMA (ID) ON DELETE CASCADE
    );

    CREATE TABLE KAPITEL
    (
        KURS_ID    INT          NOT NULL,
        KAPITEL_NR INT          NOT NULL,
        DEFINITION VARCHAR(255) NOT NULL,
        CONSTRAINT PRIMARY KEY (KURS_ID, KAPITEL_NR),
        FOREIGN KEY (KURS_ID) REFERENCES KURSE (ID) ON DELETE CASCADE
    );

    CREATE TABLE ERKLAERUNGEN
    (
        ERKLAERUNGEN_NR INT          NOT NULL,
        KURS_ID         INT          NOT NULL,
        KAPITEL_NR      INT          NOT NULL,
        HEADER          VARCHAR(255) NOT NULL,
        ERKLAERUNG      VARCHAR(255) NOT NULL,
        IMG_SRC         VARCHAR(255),
        CONSTRAINT PRIMARY KEY (KURS_ID, KAPITEL_NR,ERKLAERUNGEN_NR),
        FOREIGN KEY (KURS_ID, KAPITEL_NR) REFERENCES KAPITEL (KURS_ID, KAPITEL_NR) ON DELETE CASCADE
    );

    CREATE TABLE AUFGABEN
    (
        ID               INT AUTO_INCREMENT PRIMARY KEY,
        AUFGABEN_NR      INT          NOT NULL,
        KURS_ID          INT          NOT NULL,
        KAPITEL_NR       INT          NOT NULL,
        AUFGABENSTELLUNG VARCHAR(255) NOT NULL,
        TIPP             VARCHAR(255),
        IMG_SRC          VARCHAR(255),
        CONSTRAINT  UNIQUE (KURS_ID,KAPITEL_NR,AUFGABEN_NR),
        FOREIGN KEY (KURS_ID,KAPITEL_NR) REFERENCES KAPITEL (KURS_ID, KAPITEL_NR)  ON DELETE CASCADE
    );

    CREATE TABLE LOESUNGEN
    (
        ID         INT AUTO_INCREMENT PRIMARY KEY,
        AUFGABE_ID INT          NOT NULL,
        LOESUNG    VARCHAR(255) NOT NULL,
        FOREIGN KEY (AUFGABE_ID) REFERENCES AUFGABEN (ID) ON DELETE CASCADE
    );
