USE SCHULDB;
DROP TABLE IF EXISTS LOESUNGEN;
DROP TABLE IF EXISTS AUFGABEN;
DROP TABLE IF EXISTS ERKLAERUNGEN;
DROP TABLE IF EXISTS KAPITEL;
DROP TABLE IF EXISTS KURSE;
DROP TABLE IF EXISTS THEMA;
DROP TABLE IF EXISTS FAECHER;


CREATE TABLE FAECHER
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE THEMA
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL,
    FAECHER_ID INT,
    FOREIGN KEY (FAECHER_ID) REFERENCES FAECHER (ID) ON DELETE CASCADE
);

CREATE TABLE KURSE
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    TITEL        VARCHAR(255) NOT NULL,
    AUTHOR       VARCHAR(255) NOT NULL,
    IMG          VARCHAR(255),
    BESCHREIBUNG TEXT,
    FAECHER_ID   INT,
    THEMA_ID   INT,
    FOREIGN KEY (FAECHER_ID) REFERENCES FAECHER (ID) ON DELETE CASCADE,
    FOREIGN KEY (THEMA_ID) REFERENCES THEMA(ID) on DELETE CASCADE
);

CREATE TABLE KAPITEL
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    KURS_ID    INT  NOT NULL,
    DEFINITION TEXT NOT NULL,
    FOREIGN KEY (KURS_ID) REFERENCES KURSE (ID) ON DELETE CASCADE
);

CREATE TABLE ERKLAERUNGEN
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    KAPITEL_ID INT          NOT NULL,
    HEADER     VARCHAR(255) NOT NULL,
    ERKLAERUNG TEXT         NOT NULL,
    IMG_SRC    VARCHAR(255),
    FOREIGN KEY (KAPITEL_ID) REFERENCES KAPITEL (ID) ON DELETE CASCADE
);

CREATE TABLE AUFGABEN
(
    ID               INT AUTO_INCREMENT PRIMARY KEY,
    KAPITEL_ID       INT  NOT NULL,
    AUFGABENSTELLUNG TEXT NOT NULL,
    TIPP             TEXT,
    IMG_SRC          VARCHAR(255),
    FOREIGN KEY (KAPITEL_ID) REFERENCES KAPITEL (ID) ON DELETE CASCADE
);

CREATE TABLE LOESUNGEN
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    AUFGABE_ID INT  NOT NULL,
    LOESUNG    TEXT NOT NULL,
    FOREIGN KEY (AUFGABE_ID) REFERENCES AUFGABEN (ID) ON DELETE CASCADE
);
